version: "3.8"
networks:
  card-net:
    driver: overlay
services:
  nginx:
    image: nginx:latest
    ports:
      - published: 80
        target: 80
        protocol: tcp
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - "front-end"
    networks:
      - "card-net"
  front-end:
    image: jwearn1999/card-generate-front:v8
    build: ./front-end
    networks:
      - "card-net"
    depends_on:
      - "cardvalue-api"
      - "cardsuit-api"
      - "card-api"
    # environment:
    #   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  cardvalue-api:
    image: jwearn1999/card-generate-value:v1
    build: ./cardvalue-api
    networks:
      - "card-net"
  cardsuit-api:
    image: jwearn1999/card-generate-suit:v1
    build: ./cardsuit-api
    deploy:
      replicas: 3
    networks:
      - "card-net"
  card-api:
    image: jwearn1999/card-generate:v4
    build: ./card-api
    networks:
      - "card-net"