version: "3.8"
networks:
  card-net:
    driver: overlay
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - published: 80
        target: 80
        protocol: tcp
    volumes:
      - type: bind
        source: ./nginx.conf
        target: ./nginx.conf
    networks:
      - "card-net"
    depends_on:
      - "front-end"
  front-end:
    image: jwearn1999/card-generate-front:latest
    build: ./front-end
    networks:
      - "card-net"
    # depends_on:
    #   - "cardvalue-api"
    #   - "cardsuit-api"
    #   - "card-api"
    # environment:
    #   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  cardvalue-api:
    image: jwearn1999/card-generate-value:latest
    build: ./cardvalue-api
    deploy:
      replicas: 3
    networks:
      - "card-net"
  cardsuit-api:
    image: jwearn1999/card-generate-suit:latest
    build: ./cardsuit-api
    deploy:
      replicas: 3
    networks:
      - "card-net"
  card-api:
    image: jwearn1999/card-generate:latest
    build: ./card-api
    deploy:
      replicas: 3
    networks:
      - "card-net"