version: "3.8"
services:
  front-end:
    image: jwearn1999/card-generate-front:latest
    build: ./front-end
    networks:
      - "card-net"
    depends_on:
      - "cardvalue-api"
      - "cardsuit-api"
      - "card-api"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  cardvalue-api:
    image: jwearn1999/card-generate-value:latest
    build: ./cardvalue-api
    networks:
      - "card-net"
  cardsuit-api:
    image: jwearn1999/card-generate-suit:latest
    build: ./cardsuit-api
    networks:
      - "card-net"
  card-api:
    image: jwearn1999/card-generate:latest
    build: ./card-api
    networks:
      - "card-net"
  nginx:
    image: nginx:latest
    ports:
      - published: 80
        target: 80
        protocol: tcp
    volumes:
      - type: bind
        source: ./nginx.conf
        target: ./etc/nginc/nginx.conf
    networks:
      - "card-net"
    depends_on:
      - "front-end"
networks:
  card-net:
    # driver: overlay