version: "3.8"
volumes:
  card-vol:
networks:
  card-net:
    driver: overlay
services:
  mysql:
    image: jwearn1999/card-generate-db:v9
    build: ./database
    volumes:
      - type: volume
        source: card-vol
        target: /var/lib/mysql
    networks:
      - "card-net"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: card_db
  nginx:
    image: nginx:latest
    ports:
      - published: 80
        target: 80
        protocol: tcp
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - "front-end"
    networks:
      - "card-net"  
  front-end:
    image: jwearn1999/card-generate-front:v27
    build: ./front-end
    networks:
      - "card-net"
    depends_on:
      - "mysql"
      - "cardvalue-api"
      - "cardsuit-api"
      - "card-api"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  cardvalue-api:
    image: jwearn1999/card-generate-value:v5
    build: ./cardvalue-api
    networks:
      - "card-net"
  cardsuit-api:
    image: jwearn1999/card-generate-suit:v4
    build: ./cardsuit-api
    deploy:
      replicas: 3
    networks:
      - "card-net"
  card-api:
    image: jwearn1999/card-generate:v8
    build: ./card-api
    networks:
      - "card-net"