- hosts: devvm
  become: true
  roles:
  - python
  - docker
  - docker-compose
  vars:
    docker_user: jwearn

- hosts: ciservers
  become: true
  roles:
  - python
  - docker
  - docker-compose
  - jenkins
  vars:
    docker_user: jenkins

- hosts: swarmmanagers
  become: true
  roles:
  - docker
  - swarm-manager
  tasks:
  - name: add ansible user to docker group
    user:
      name: jwearn
      groups: docker
      append: yes
  vars:
    docker_user: jenkins

- hosts: swarmworkers
  become: true
  roles:
  - docker
  - swarm-worker
  vars:
    docker_user: jwearn